// src/components/modals/CreateGroupModal.tsx
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { CURRENCIES } from "@/utils/currencies";
import { errorMessage } from "@/utils/errors";
import { PlusIcon, XIcon } from "lucide-react";
import type React from "react";
import { useEffect, useState } from "react";

interface CreateGroupModalProps {
  isOpen: boolean;
  onClose: () => void;
  /** The first participant is the user; the backend records them as "you". */
  onCreateGroup: (name: string, currency: string, participants: string[]) => Promise<void>;
  /** Suggested name for the user. */
  ownName: string;
}

interface ParticipantField {
  id: string;
  name: string;
}

const SELF_ID = "p-self";

const initialParticipants = (ownName = ""): ParticipantField[] => [
  { id: SELF_ID, name: ownName },
  { id: "p-init-2", name: "" },
  { id: "p-init-3", name: "" },
];

export const CreateGroupModal: React.FC<CreateGroupModalProps> = ({
  isOpen,
  onClose,
  onCreateGroup,
  ownName,
}) => {
  const [name, setName] = useState("");
  const [currency, setCurrency] = useState("EUR");
  const [participants, setParticipants] = useState<ParticipantField[]>(initialParticipants);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Suggest the user's name, without overwriting what they typed.
  useEffect(() => {
    if (!isOpen) return;
    setParticipants((current) =>
      current.map((p) => (p.id === SELF_ID && !p.name.trim() ? { ...p, name: ownName } : p))
    );
  }, [isOpen, ownName]);

  const handleAddParticipantField = () => {
    setParticipants([...participants, { id: `p-${Date.now()}-${Math.random()}`, name: "" }]);
  };

  const handleParticipantChange = (id: string, value: string) => {
    setParticipants(participants.map((p) => (p.id === id ? { ...p, name: value } : p)));
  };

  const handleRemoveParticipantField = (id: string) => {
    if (id === SELF_ID) return;
    setParticipants(participants.filter((p) => p.id !== id));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmedName = name.trim();
    // The user's own name stays first.
    const validParticipants = participants.map((p) => p.name.trim()).filter((p) => p.length > 0);

    if (!trimmedName) {
      setError("Please enter a group name.");
      return;
    }
    if (!participants[0]?.name.trim()) {
      setError("Please enter your name.");
      return;
    }

    setSubmitting(true);
    setError(null);
    try {
      await onCreateGroup(trimmedName, currency, validParticipants);
      setName("");
      setCurrency("EUR");
      setParticipants(initialParticipants(ownName));
      onClose();
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Create New Group</DialogTitle>
          <DialogDescription>
            A trip, a flatshare, a dinner… You can add more people later.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit}>
          <FieldGroup>
            <Field>
              <FieldLabel htmlFor="input-group-name">Group name</FieldLabel>
              <Input
                id="input-group-name"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Summer Vacation, Roommates"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="select-group-currency">Currency</FieldLabel>
              <Select value={currency} onValueChange={setCurrency}>
                <SelectTrigger id="select-group-currency" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent position="popper">
                  {CURRENCIES.map((c) => (
                    <SelectItem key={c.code} value={c.code}>
                      {c.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </Field>

            <FieldSet>
              <FieldLegend variant="label">Participants</FieldLegend>
              <div className="space-y-2">
                {participants.map((p, idx) => (
                  <div key={p.id} className="flex items-center gap-2">
                    <Input
                      value={p.name}
                      onChange={(e) => handleParticipantChange(p.id, e.target.value)}
                      placeholder={p.id === SELF_ID ? "Your name" : `Participant ${idx + 1}`}
                      aria-label={p.id === SELF_ID ? "Your name" : `Participant ${idx + 1}`}
                    />
                    {p.id === SELF_ID ? (
                      <span className="w-9 shrink-0 text-center text-xs text-muted-foreground">
                        You
                      </span>
                    ) : (
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => handleRemoveParticipantField(p.id)}
                        aria-label={`Remove participant ${idx + 1}`}
                      >
                        <XIcon />
                      </Button>
                    )}
                  </div>
                ))}
              </div>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="self-start"
                onClick={handleAddParticipantField}
              >
                <PlusIcon data-icon="inline-start" />
                Add person
              </Button>
            </FieldSet>

            <FieldError>{error}</FieldError>
          </FieldGroup>

          <DialogFooter className="mt-6">
            <DialogClose asChild>
              <Button type="button" variant="outline">
                Cancel
              </Button>
            </DialogClose>
            <Button type="submit" disabled={submitting}>
              {submitting && <Spinner data-icon="inline-start" />}
              Create Group
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

// src/components/modals/CreateGroupModal.svelte
<script lang="ts">
  import PlusIcon from "@lucide/svelte/icons/plus";
  import XIcon from "@lucide/svelte/icons/x";
  import { untrack } from "svelte";
  import { Button } from "@/components/ui/button";
  import * as Dialog from "@/components/ui/dialog";
  import * as Field from "@/components/ui/field";
  import { Input } from "@/components/ui/input";
  import * as Select from "@/components/ui/select";
  import { Spinner } from "@/components/ui/spinner";
  import { createGroup } from "@/lib/actions";
  import { dialogs } from "@/lib/state/dialogs.svelte";
  import { session } from "@/lib/state/session.svelte";
  import { CURRENCIES } from "@/utils/currencies";
  import { errorMessage } from "@/utils/errors";

  interface ParticipantField {
    id: string;
    name: string;
  }

  const SELF_ID = "p-self";
  const initialParticipants = (ownName = ""): ParticipantField[] => [
    { id: SELF_ID, name: ownName },
    { id: "p-init-2", name: "" },
    { id: "p-init-3", name: "" },
  ];

  const ownName = $derived(session.account?.username ?? "");

  let name = $state("");
  let currency = $state("EUR");
  let participants = $state<ParticipantField[]>(initialParticipants());
  let submitting = $state(false);
  let error = $state<string | null>(null);

  // Suggest the user's name when the dialog opens, without overwriting what they typed.
  $effect.pre(() => {
    if (!dialogs.createGroup) return;
    const suggested = ownName;
    untrack(() => {
      const self = participants[0];
      if (self && !self.name.trim()) self.name = suggested;
    });
  });

  function removeParticipant(id: string) {
    if (id !== SELF_ID) participants = participants.filter((p) => p.id !== id);
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    const trimmedName = name.trim();
    // The user's own name stays first.
    const names = participants.map((p) => p.name.trim()).filter((p) => p.length > 0);
    if (!trimmedName) {
      error = "Please enter a group name.";
      return;
    }
    if (!participants[0]?.name.trim()) {
      error = "Please enter your name.";
      return;
    }
    submitting = true;
    error = null;
    try {
      await createGroup(trimmedName, currency, names);
      name = "";
      currency = "EUR";
      participants = initialParticipants(ownName);
      dialogs.createGroup = false;
    } catch (err) {
      error = errorMessage(err);
    } finally {
      submitting = false;
    }
  }
</script>

<Dialog.Root bind:open={dialogs.createGroup}>
  <Dialog.Content class="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-md">
    <Dialog.Header>
      <Dialog.Title>Create New Group</Dialog.Title>
      <Dialog.Description>
        A trip, a flatshare, a dinner… You can add more people later.
      </Dialog.Description>
    </Dialog.Header>

    <form onsubmit={handleSubmit}>
      <Field.Group>
        <Field.Field>
          <Field.Label for="input-group-name">Group name</Field.Label>
          <Input
            id="input-group-name"
            required
            bind:value={name}
            placeholder="e.g. Summer Vacation, Roommates"
          />
        </Field.Field>

        <Field.Field>
          <Field.Label for="select-group-currency">Currency</Field.Label>
          <Select.Root type="single" bind:value={currency}>
            <Select.Trigger id="select-group-currency" class="w-full">
              {CURRENCIES.find((c) => c.code === currency)?.label ?? currency}
            </Select.Trigger>
            <Select.Content>
              {#each CURRENCIES as c (c.code)}
                <Select.Item value={c.code} label={c.label} />
              {/each}
            </Select.Content>
          </Select.Root>
        </Field.Field>

        <Field.Set>
          <Field.Legend variant="label">Participants</Field.Legend>
          <div class="space-y-2">
            {#each participants as p, idx (p.id)}
              <div class="flex items-center gap-2">
                <Input
                  bind:value={p.name}
                  placeholder={p.id === SELF_ID ? "Your name" : `Participant ${idx + 1}`}
                  aria-label={p.id === SELF_ID ? "Your name" : `Participant ${idx + 1}`}
                />
                {#if p.id === SELF_ID}
                  <span class="w-9 shrink-0 text-center text-xs text-muted-foreground">You</span>
                {:else}
                  <Button
                    variant="ghost"
                    size="icon"
                    onclick={() => removeParticipant(p.id)}
                    aria-label={`Remove participant ${idx + 1}`}
                  >
                    <XIcon />
                  </Button>
                {/if}
              </div>
            {/each}
          </div>
          <Button
            variant="ghost"
            size="sm"
            class="self-start"
            onclick={() => participants.push({ id: `p-${Date.now()}-${Math.random()}`, name: "" })}
          >
            <PlusIcon data-icon="inline-start" />
            Add person
          </Button>
        </Field.Set>

        {#if error}
          <Field.Error>{error}</Field.Error>
        {/if}
      </Field.Group>

      <Dialog.Footer class="mt-6">
        <Dialog.Close>
          {#snippet child({ props })}
            <Button {...props} variant="outline">Cancel</Button>
          {/snippet}
        </Dialog.Close>
        <Button type="submit" disabled={submitting}>
          {#if submitting}
            <Spinner data-icon="inline-start" />
          {/if}
          Create Group
        </Button>
      </Dialog.Footer>
    </form>
  </Dialog.Content>
</Dialog.Root>
