// src/components/modals/JoinGroupModal.tsx
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Spinner } from "@/components/ui/spinner";
import { Textarea } from "@/components/ui/textarea";
import { useNativeFeatures } from "@/services/native";
import { errorMessage } from "@/utils/errors";
import { ScanQrCodeIcon } from "lucide-react";
import type React from "react";
import { useEffect, useState } from "react";

interface JoinGroupModalProps {
  isOpen: boolean;
  onClose: () => void;
  onJoinGroup: (inviteCode: string) => Promise<void>;
  /** Pre-fills the invite, say from a link the app was opened with. */
  initialCode?: string;
  initialError?: string | null;
  /** Scans an invite's QR code instead; offered where the device has a camera scanner. */
  onScan: () => void;
}

export const JoinGroupModal: React.FC<JoinGroupModalProps> = ({
  isOpen,
  onClose,
  onJoinGroup,
  initialCode = "",
  initialError = null,
  onScan,
}) => {
  const [code, setCode] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const native = useNativeFeatures();

  useEffect(() => {
    if (!isOpen) return;
    setCode(initialCode);
    setError(initialError);
  }, [isOpen, initialCode, initialError]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) return;
    setSubmitting(true);
    setError(null);
    try {
      await onJoinGroup(code.trim());
      onClose();
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Join a Group</DialogTitle>
          <DialogDescription>
            Open the invite link a member sent you, or paste it here. To get one, a member opens the
            group and taps Invite.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <FieldGroup>
            {native.scan && (
              <Button type="button" variant="outline" size="lg" onClick={onScan}>
                <ScanQrCodeIcon data-icon="inline-start" />
                Scan QR Code
              </Button>
            )}
            <Field>
              <FieldLabel htmlFor="input-invite-code">Invite link</FieldLabel>
              <Textarea
                id="input-invite-code"
                required
                rows={3}
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder="https://…/join#…"
                spellCheck={false}
                autoCapitalize="off"
                autoCorrect="off"
                className="resize-none font-mono text-xs break-all"
              />
            </Field>
            <FieldError>{error}</FieldError>
          </FieldGroup>
          <DialogFooter className="mt-6">
            <DialogClose asChild>
              <Button type="button" variant="outline">
                Cancel
              </Button>
            </DialogClose>
            <Button type="submit" disabled={submitting}>
              {submitting && <Spinner data-icon="inline-start" />}
              Join Group
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

// src/components/modals/JoinGroupModal.svelte
<script lang="ts">
  import ScanQrCodeIcon from "@lucide/svelte/icons/scan-qr-code";
  import { untrack } from "svelte";
  import { Button } from "@/components/ui/button";
  import * as Dialog from "@/components/ui/dialog";
  import * as Field from "@/components/ui/field";
  import { Spinner } from "@/components/ui/spinner";
  import { Textarea } from "@/components/ui/textarea";
  import { joinGroup, scanInvite } from "@/lib/actions";
  import { dialogs } from "@/lib/state/dialogs.svelte";
  import { nativeFeatures } from "@/services/native.svelte";
  import { errorMessage } from "@/utils/errors";

  let code = $state("");
  let submitting = $state(false);
  let error = $state<string | null>(null);

  // Opens with the invite from a link or a scan, if any, and why joining with it failed.
  $effect.pre(() => {
    if (!dialogs.join.open) return;
    untrack(() => {
      code = dialogs.join.code;
      error = dialogs.join.error;
    });
  });

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!code.trim()) return;
    submitting = true;
    error = null;
    try {
      await joinGroup(code.trim());
      dialogs.join.open = false;
    } catch (err) {
      error = errorMessage(err);
    } finally {
      submitting = false;
    }
  }
</script>

<Dialog.Root bind:open={dialogs.join.open}>
  <Dialog.Content class="sm:max-w-md">
    <Dialog.Header>
      <Dialog.Title>Join a Group</Dialog.Title>
      <Dialog.Description>
        Open the invite link a member sent you, or paste it here. To get one, a member opens the
        group and taps Invite.
      </Dialog.Description>
    </Dialog.Header>
    <form onsubmit={handleSubmit}>
      <Field.Group>
        {#if nativeFeatures.scan}
          <Button variant="outline" size="lg" onclick={scanInvite}>
            <ScanQrCodeIcon data-icon="inline-start" />
            Scan QR Code
          </Button>
        {/if}
        <Field.Field>
          <Field.Label for="input-invite-code">Invite link</Field.Label>
          <Textarea
            id="input-invite-code"
            required
            rows={3}
            bind:value={code}
            placeholder="https://…/join#…"
            spellcheck={false}
            autocapitalize="off"
            class="resize-none font-mono text-xs break-all"
          />
        </Field.Field>
        {#if error}
          <Field.Error>{error}</Field.Error>
        {/if}
      </Field.Group>
      <Dialog.Footer class="mt-6">
        <Dialog.Close>
          {#snippet child({ props })}
            <Button {...props} variant="outline">Cancel</Button>
          {/snippet}
        </Dialog.Close>
        <Button type="submit" disabled={submitting}>
          {#if submitting}
            <Spinner data-icon="inline-start" />
          {/if}
          Join Group
        </Button>
      </Dialog.Footer>
    </form>
  </Dialog.Content>
</Dialog.Root>
