// src/components/workspace/SettleUpTab.tsx
import { Amount } from "@/components/common/Amount";
import { HelpPopover } from "@/components/common/HelpPopover";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty";
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemMedia,
  ItemTitle,
} from "@/components/ui/item";
import type { Group, SettlementTransfer } from "@/types";
import { CheckIcon, CircleCheckBigIcon, PlusIcon } from "lucide-react";
import type React from "react";

interface SettleUpTabProps {
  group: Group;
  settlements: SettlementTransfer[];
  onOpenReimburse: () => void;
  onMarkAsPaid: (fromId: string, toId: string, amount: string) => void;
}

export const SettleUpTab: React.FC<SettleUpTabProps> = ({
  group,
  settlements,
  onOpenReimburse,
  onMarkAsPaid,
}) => {
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-1">
          <h2 className="font-medium">Suggested payments</h2>
          <HelpPopover title="Optimal settlement plan">
            The fewest direct payments that settle every debt in the group. Mark one as paid once
            the money is sent.
          </HelpPopover>
        </div>
        {settlements.length > 0 && group.expenses.length > 0 && (
          <Button onClick={onOpenReimburse}>
            <PlusIcon data-icon="inline-start" />
            Record Reimbursement
          </Button>
        )}
      </div>

      {settlements.length === 0 ? (
        <Empty className="border border-dashed">
          <EmptyHeader>
            <EmptyMedia variant="icon" className="text-positive">
              <CircleCheckBigIcon />
            </EmptyMedia>
            <EmptyTitle>All settled up!</EmptyTitle>
            <EmptyDescription>No one in this group owes anything to anyone.</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <ul className="space-y-2">
          {settlements.map((s) => (
            <li key={`${s.from_id}-${s.to_id}`}>
              <Item variant="outline">
                <ItemMedia>
                  <Avatar>
                    <AvatarFallback>{s.from_name.charAt(0).toUpperCase()}</AvatarFallback>
                  </Avatar>
                </ItemMedia>
                <ItemContent>
                  <ItemTitle>
                    <span>
                      <span className="text-negative">{s.from_name}</span> pays{" "}
                      <span className="text-positive">{s.to_name}</span>
                    </span>
                  </ItemTitle>
                  <ItemDescription>Direct reimbursement</ItemDescription>
                </ItemContent>
                <ItemActions>
                  <Amount
                    cents={s.amount_cents}
                    currency={group.currency}
                    className="font-semibold"
                  />
                  <Button
                    variant="outline"
                    onClick={() =>
                      onMarkAsPaid(s.from_id, s.to_id, (s.amount_cents / 100).toFixed(2))
                    }
                  >
                    <CheckIcon data-icon="inline-start" />
                    Mark as Paid
                  </Button>
                </ItemActions>
              </Item>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

// src/components/workspace/SettleUpTab.svelte
<script lang="ts">
  import CheckIcon from "@lucide/svelte/icons/check";
  import CircleCheckBigIcon from "@lucide/svelte/icons/circle-check-big";
  import PlusIcon from "@lucide/svelte/icons/plus";
  import Amount from "@/components/common/Amount.svelte";
  import HelpPopover from "@/components/common/HelpPopover.svelte";
  import * as Avatar from "@/components/ui/avatar";
  import { Button } from "@/components/ui/button";
  import * as Empty from "@/components/ui/empty";
  import * as Item from "@/components/ui/item";
  import { dialogs } from "@/lib/state/dialogs.svelte";
  import { openGroup } from "@/lib/state/groups.svelte";
  import type { Group } from "@/types";

  let { group }: { group: Group } = $props();

  const settlements = $derived(openGroup.settlements);
</script>

<div class="space-y-3">
  <div class="flex flex-wrap items-center justify-between gap-2">
    <div class="flex items-center gap-1">
      <h2 class="font-medium">Suggested payments</h2>
      <HelpPopover title="Optimal settlement plan">
        The fewest direct payments that settle every debt in the group. Mark one as paid once the
        money is sent.
      </HelpPopover>
    </div>
    {#if settlements.length > 0 && group.expenses.length > 0}
      <Button onclick={() => dialogs.openReimburse()}>
        <PlusIcon data-icon="inline-start" />
        Record Reimbursement
      </Button>
    {/if}
  </div>

  {#if settlements.length === 0}
    <Empty.Root class="border border-dashed">
      <Empty.Header>
        <Empty.Media variant="icon" class="text-positive"><CircleCheckBigIcon /></Empty.Media>
        <Empty.Title>All settled up!</Empty.Title>
        <Empty.Description>No one in this group owes anything to anyone.</Empty.Description>
      </Empty.Header>
    </Empty.Root>
  {:else}
    <ul class="space-y-2">
      {#each settlements as s (`${s.from_id}-${s.to_id}`)}
        <li>
          <Item.Root variant="outline">
            <Item.Media>
              <Avatar.Root>
                <Avatar.Fallback>{s.from_name.charAt(0).toUpperCase()}</Avatar.Fallback>
              </Avatar.Root>
            </Item.Media>
            <Item.Content>
              <Item.Title>
                <span>
                  <span class="text-negative">{s.from_name}</span>
                  pays
                  <span class="text-positive">{s.to_name}</span>
                </span>
              </Item.Title>
              <Item.Description>Direct reimbursement</Item.Description>
            </Item.Content>
            <Item.Actions>
              <Amount cents={s.amount_cents} currency={group.currency} class="font-semibold" />
              <Button
                variant="outline"
                onclick={() =>
                  dialogs.openReimburse({
                    fromId: s.from_id,
                    toId: s.to_id,
                    amount: (s.amount_cents / 100).toFixed(2),
                  })}
              >
                <CheckIcon data-icon="inline-start" />
                Mark as Paid
              </Button>
            </Item.Actions>
          </Item.Root>
        </li>
      {/each}
    </ul>
  {/if}
</div>
