// src/components/common/HelpPopover.svelte
<script lang="ts">
  import CircleHelpIcon from "@lucide/svelte/icons/circle-question-mark";
  import type { Snippet } from "svelte";
  import { Button } from "@/components/ui/button";
  import * as Popover from "@/components/ui/popover";

  /** A "?" button that explains something in a popover, instead of text always on screen. */
  let { title, children }: { title: string; children: Snippet } = $props();
</script>

<Popover.Root>
  <Popover.Trigger>
    {#snippet child({ props })}
      <Button
        {...props}
        variant="ghost"
        size="icon-sm"
        aria-label={`About ${title.toLowerCase()}`}
        class="text-muted-foreground"
      >
        <CircleHelpIcon />
      </Button>
    {/snippet}
  </Popover.Trigger>
  <Popover.Content align="start" class="w-72">
    <Popover.Header>
      <Popover.Title>{title}</Popover.Title>
      <Popover.Description>{@render children()}</Popover.Description>
    </Popover.Header>
  </Popover.Content>
</Popover.Root>

// src/components/common/HelpPopover.tsx
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "@/components/ui/popover";
import { CircleHelpIcon } from "lucide-react";
import type React from "react";

interface HelpPopoverProps {
  title: string;
  children: React.ReactNode;
}

/** A "?" button that explains something in a popover, instead of text always on screen. */
export const HelpPopover: React.FC<HelpPopoverProps> = ({ title, children }) => (
  <Popover>
    <PopoverTrigger asChild>
      <Button
        variant="ghost"
        size="icon-sm"
        aria-label={`About ${title.toLowerCase()}`}
        className="text-muted-foreground"
      >
        <CircleHelpIcon />
      </Button>
    </PopoverTrigger>
    <PopoverContent align="start" className="w-72">
      <PopoverHeader>
        <PopoverTitle>{title}</PopoverTitle>
        <PopoverDescription>{children}</PopoverDescription>
      </PopoverHeader>
    </PopoverContent>
  </Popover>
);
